README.md
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatch.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/scheduledperations/PendingTransactionBatchTests.kt

Add README file
Refactored PendingTransactionAnalyzer class package
Those modifications are needed in order to document the project and clear code base packaging
Local test
expected)

feat: readme + refactoring batch class package

---

README.md
pom.xml
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt

- Upgraded ecommerce-commons version to 0.8.0 in order to handle new statuses
- Reinforced unit tests adding additionals checks:
1. Explicitate the transaction status for which check if expiration event is sent or not
2. Add check that all transactions statuses, as enumerated into TransactionStatusDto, are covered by tests
The following new statuses handling have been added:
- `CANCELLATION_REQUESTED ` -> expiration event sent
- `NOTIFIED_OK ` -> expiration event not sent
- `NOTIFIED_KO ` -> expiration event not sent
- `REFUND_REQUESTED ` -> expiration event not sent
- `REFUND_ERROR ` -> expiration event not sent
- `CANCELLATION_EXPIRED ` -> expiration event not sent
Those modifications are needed to properly handling new transactions statuses.
Unit tests modifications are needed to …

feat: upgrade commons version handling new statuses

---

helm/values-dev.yaml
helm/values-uat.yaml
pom.xml

Update ecommerce-commons to latest minor version
Configured queue for use the new ones as configured here pagopa/pagopa-infra#770
Configured queue where batch has to send event for dispatcher
Junit tests + dev deploy
expected)

feat: upgrade commons version + expiration queue configuration

---

README.md
pom.xml
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzerTests.kt

Upgrade commons version
Set NOTIFIED_KO as status for which send expiration event
Those modifications are needed in order to send expiration event also for transactions stuck into NOTIFIED_KO status
Junit tests
expected)

feat: upgrade commons version

---

.devops/azure-templates/chart-current-version.yml
.devops/azure-templates/chart-github-release.yml
.devops/azure-templates/helm-microservice-chart-deploy.yml
.devops/deploy-pipelines.yml

Update deploy pipeline to use the same template as used for all other ecommerce modules
With this modification deploy pipeline will be aligned to all other ecommerce modules.
Beside that with ecommerce deploy pipelines template the module can be deployed to both DEV and UAT environment in one single pipeline run
Deploy pipeline execution in DEV environment
expected)

feat: update deploy pipelines

---

Dockerfile
helm/values-dev.yaml
helm/values-uat.yaml

Add ELK agent
Add ELK agent
DEV deployment
See https://kibana.dev.platform.pagopa.it/kibana/app/apm/services/pagopa-ecommerce-transactions-scheduler-service/overview?comparisonEnabled=true&environment=ENVIRONMENT_ALL&kuery=&latencyAggregationType=avg&offset=1d&rangeFrom=now-1h&rangeTo=now&serviceGroup=&transactionType=request
expected)

feat: add elk agent

---

pom.xml

Update commons version to 0.13.0
expected)

update commons version 0.13.0

---

pom.xml

Update ecommerce-commons version
Update ecommerce-commons version
Juni tests
expected)

feat: update commons version

---

src/main/resources/application.properties

Change mongo readPreference to `primaryPreferred`
With this mode all read operations will be redirect to secondary partition if available with fallback on primary ones.
The `maxStalenessSeconds` parameter is set to a value of 3600 seconds in order to block reads from a replica older that 1 hours due to the batch nature of the performed operations that recover all transactions older than 1 hour 
See https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/readpreference-global-distribution#read-using-read-preference-mode
Those modifications are needed in order to redirect all read operations to the secondary replica since data required by the batch is older than 1 hour

feat: mongo read preference mode

---

src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
src/main/resources/application.properties
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt

Handle expiration status for transactions stuck in `CANCELLATION_REQUESTED` or `CLOSURE_ERROR` coming from a user canceled transaction flow
Those modifications are needed in order to properly update the above mentioned transactions in `CANCELLATION_EXPIRED` status
Junit tests + test with ecommerce local
expected)

Chk 1517 handle cancellation requested status

---

src/main/resources/application.properties

Fix spring server port
Fix spring server port
expected)

fix: server port

---

helm/values-prod.yaml

feat(helm): CHK-1539 Add helm value for prod

---

pom.xml
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt

Update commons version to 0.16.2
Update commons to the latest version
expected)

fix: update commons version

---

.devops/deploy-pipelines.yml

Add kubectl installer for uat deploy pipelines
Add kubectl installer for uat deploy pipelines
expected)

fix: add kubectl installer deploy pipelines

---

pom.xml

feat(common): update common for view name

---

pom.xml

Update common version
expected)

[CHK-1636] update common version

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
src/main/resources/logback-spring.xml

- Add logback ECS encoder to format log in json ECS format
- Disable APM agent log sending since logs will be ingested by filebeat agent
Those modifications are needed in order to properly format log in json ECS format
Local run
`{"@timestamp":"2023-06-21T08:27:10.541Z","log.level": "INFO","message":"Started TransactionsSchedulerApplicationKt in 2.072 seconds (JVM running for 2.87)","ecs.version": "1.2.0","service.name":"pagopa-ecommerce-transactions-scheduler-service","service.version":"0.2.3","event.dataset":"pagopa-ecommerce-transactions-scheduler-service","process.thread.name":"main","log.logger":"it.pagopa.ecommerce.transactions.scheduler.TransactionsSchedulerApplicationKt"}`
expected)

feat(logging): format log in ecs json format

---

README.md
helm/values-prod.yaml
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/EventPublisher.kt
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisher.kt
src/main/resources/application.properties
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/TransactionExpiredEventPublisherTests.kt

Add parameter to explicit set events TTL value. This value is parameterized with `TRANSIENT_QUEUES_TTL_MINUTES` (default value 7 days) and set to 30 days in prod configuration.
Those modifications are needed in order to override the 7 days default values of the Azure SDK
Junit tests + local test with ecommerce local

Chk 1647 events ttl

---

.github/workflows/chart_github_release.yml

fix(release): add release action

---

pom.xml

Updated commons version from 0.18.2 to 0.18.3
expected)

update commons version from 0.18.2. to 0.18.3

---

.github/workflows/deploy.yml

Change deploy pipeline trigger to push on main branch
Change deploy pipeline trigger to push on main branch
expected)

Fix deploy parameters

---

.github/actions/check-pr-semver-labels/action.yml

Fix check pr label code for retrieve pr labels taking PR number from merge commit message
Those modifications are needed in order to retrieve PR number from merge commit in case the action is run against main PR merge 
expected)

fix(deploy-action): fix issue number retrieve code from merge commit

---

.github/actions/check-pr-semver-labels/action.yml

Fix issue number check
Fix issue number check
expected)

Deploy trigger fix

---

.github/actions/check-pr-semver-labels/action.yml

Fix issue number refs
Fix issue number refs
expected)

fix(check-pr-action):issue number

---

.github/actions/check-pr-semver-labels/action.yml

Fix issue number ref
Fix issue number ref
expected)

fix(check-pr-action): issue number ref

---

.github/workflows/deploy.yml

Fix skipBuild parameter value to false (lowercase)
pretty printed json values for better readability
Those modifications are needed to properly trigger azure devops pipeline
expected)

fix(deploy-action): change skipBuild parameter value

---

.github/workflows/deploy.yml

fix(deploy-action): remove apex

---

.github/workflows/deploy.yml

Change skipBuild parameter to boolean value into parameter json
Change skipBuild parameter to boolean value into parameter json
expected)

Json formatting

---

.devops/deploy-pipelines.yml
.github/workflows/deploy.yml

Fix pipeline parameters
Fix pipeline parameters
expected)

fix(deploy-action): change json action parameters

---

.github/actions/check-pr-semver-labels/action.yml

Fix pr number extraction
Fix pr number extraction
expected)

fix-pr-number-extraction

---

pom.xml

Update commons version to 0.19.0
Update commons version to 0.19.0
expected)

feat(dependencies): update commons version

---

pom.xml

* update `pagopa-ecommerce-commons` version to 0.26.0
Ordinary maintenance

chore(deps): [CHK-2004] - update `commons` version to 0.26.0

---

README.md
pom.xml
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/v2/TransactionExpiredEventPublisher.kt
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/v2/TransactionExpiredEventPublisherTests.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/v1/PendingTransactionAnalyzerTests.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/v2/PendingTransactionAnalyzerTests.kt

Added handling of the new CLOSURE_REQUESTED event to handle it among the events to be passed to EXPIRED.
Added event handling of EXPIRED for transactions in CLOSURE_REQUESTED state.
expected)

[CHK-2374] Close payment async

---

helm/values-prod.yaml

- Removed apple key variable from prod helm values
expected)

hotfix: remove env variable apple pay psp from helm values prod

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoService.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoServiceTest.kt

- Use the utils class to retrieve the paymentEndToEndId from the npg getOrder call
The change is needed since the business that retrieves the field was put on ecommerce-commons
JUnit Test
expected)

[PPABV-63] Edit get payment end to end

---

.devops/deploy-pipelines.yml

Fix deployment pipeline branch checkout 
This modification is needed in order because checkout is performed on a commit previous to the release one, making deploy contain the latest code but not the version bump
expected)

fix: deployment pipeline

---

.devops/deploy-pipelines.yml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

chore: enable scaled objects

---

helm/values-uat.yaml

Fix UAT wrong ingress configuration
Fix UAT wrong ingress configuration
Api invocation in UAT env
expected)

fix: ingress value for UAT

---

pom.xml
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/EventPublisher.kt
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/v1/TransactionExpiredEventPublisher.kt
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/v2/TransactionExpiredEventPublisher.kt
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoService.kt
src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/transactionanalyzer/PendingTransactionAnalyzer.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/v1/TransactionExpiredEventPublisherTests.kt
src/test/kotlin/it/pagopa/ecommerce/transactions/scheduler/publishers/v2/TransactionExpiredEventPublisherTests.kt

Depends on https://github.com/pagopa/pagopa-ecommerce-commons/pull/231
Updated version of pagopa-commons library.
The new version of this library introduces versioning to some domain objects.
Changes in this PR mainly affect import paths.
expected)

[CHK-4116] chore(dep): update pagopa-commons library version

---

src/main/kotlin/it/pagopa/ecommerce/transactions/scheduler/services/TransactionInfoService.kt

Avoid exception in case of empty transaction activation data (such as Redirect transaction)
There were exception handling Redirect transactions where no DLQ event where written
expected)

fix: avoid exception in case of empty transaction activation data

---

Dockerfile

- add the missing step to copy the generated sha256 file for dependencies verification
In a previous PR we introduced the dependencies verification flow. This PR addresses a problem that fix some pipelines step.

fix: step copy sha256 file in dockerfile

---

.devops/deploy-pipelines.yml

- Migrated DEV and UAT build stages from inline Docker commands to use centralized `azure-pipeline-templates/templates/docker-release/template.yaml`
- Added proper GitHub token file creation for Docker build secrets
- Configured `DOCKER_BUILD_ARGS` parameter to pass GitHub token as Docker secret
The current pipeline implementation uses inline Docker build commands with duplicated logic across multiple services. This approach has several issues:
1. **Code Duplication**: Each service reimplements the same Docker build logic
2. **Maintenance Overhead**: Changes to build process require updates across all services
3. **Inconsistency**: Different services may have slight variations in build commands
This change standardizes all services to use the centralized `azure-pipeline-templates` …

[CHK-4428] restore template usage and add token file creation
